class UserNotFoundError(Exception):
    pass

class LogNotFoundError(Exception):
    pass